# ----
# Site

title: Trek View
url: "https://www.trekview.org"
baseurl: 
google_analytics_key: G-B3316TFM2H
# google_maps_javascript_api_key:
disqus_shortname: 

# Do not publish future blog posts or drafts
future: false
show_drafts: false

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: assets/images/icons/siteicon.png
description: Help build an open street-level map of the natural world
author:
  name:
twitter:
    username: trekview
    card: summary
facebook:
    app_id:
    publisher:
    admins: 
social:
  name: Trek View
  links:
    - https://www.instagram.com/trekviewed/
    - https://www.facebook.com/trekview/
    
# -----
# Build

timezone: "Europe/London"

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: "/blog/:year/:title/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - tmp
  - LICENCE
  - gulpfile.js
  - package.json
  - package-lock.json
  - node_modules


# -----------
# CloudCannon

social_icons:
  - Instagram
  - Facebook
  - Twitter
  - RSS

# -----
# _comments:
# map: Update the map location and display settings.
# latitude: Coordinates for the center marker on the map.
# longitude: Coordinates for the center marker on the map.
# zoom: The zoom level for the map.
# pricing_table: Update the information in the pricing tables.
# highlight: Emphasis the text
# color: The background colour used in the plan name and call to action.
# new_window: Open link in new window
# -----